/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 70
#define YY_END_OF_BUFFER 71
static yyconst short int yy_accept[324] =
    {   0,
       66,   66,   71,   70,   66,   66,   70,   70,   70,   24,
       70,   70,   20,   18,   17,   19,   70,   21,   64,   64,
       27,   70,   26,   69,   14,   15,   22,   69,   69,   69,
       69,   69,   69,   69,   69,   69,   69,   69,   69,   69,
       69,   69,   12,   25,   13,   66,   66,    0,   30,    0,
       62,    0,    0,    0,   10,   11,    0,    0,    0,   64,
       63,    0,    0,    0,   64,    0,   16,    0,   69,   69,
       69,   69,   69,   69,   69,   69,   69,   69,   69,   69,
       69,   69,   69,   69,   69,   69,   69,   69,   69,   69,
       69,   69,   69,   69,   69,   69,   69,   69,   28,   29,

        0,   63,    0,    1,    0,    0,   65,    0,   68,   69,
       69,   69,   69,   69,   69,   69,   69,   50,   69,   69,
       69,   69,   69,   69,   69,   69,   69,   69,   69,   69,
       69,   69,   69,   69,   69,   69,   49,   69,   69,   69,
       69,   69,    0,    0,    1,    2,   65,    0,   40,   69,
       69,   69,   69,   69,   69,   69,   69,   69,   69,   69,
        0,   69,   69,   39,   69,   69,   69,   69,   42,   69,
       69,   69,   69,   69,   69,   69,   69,   69,   69,    0,
        0,   65,    0,   69,   69,   38,    9,   69,   69,   32,
       61,   69,   53,   69,    0,   69,   69,   60,   51,   69,

       69,   69,   69,   69,   69,   69,   69,   69,   45,   69,
       69,   69,    0,    0,   65,    0,    7,   69,   69,   44,
       69,   56,    0,   69,   43,   57,   58,   41,   33,   69,
       69,    4,   69,    0,   69,   69,   69,    0,    0,   65,
        0,   48,   69,    0,   69,   36,   69,    0,   69,   69,
       69,    0,    0,   35,   23,   69,    0,    0,   63,    0,
       59,    0,    6,    0,   52,    0,   69,    5,    3,    0,
        0,   31,    0,   63,   63,   63,    0,    0,    0,    0,
       69,    0,    0,   67,   63,   63,   63,    0,    0,    0,
        0,   34,   54,    0,   63,   63,   63,    0,    0,   37,

        0,   55,   63,   63,   63,    0,    8,    0,   63,   63,
       63,    0,    0,   63,   63,   63,    0,    0,   63,   63,
       46,   47,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    1,    1,    8,    1,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   19,
       19,   19,   19,   19,   19,   19,   19,   20,   21,   22,
       23,   22,   22,   22,   24,   24,   24,   24,   24,   25,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       26,    1,   27,   28,   29,    1,   30,   31,   32,   33,

       34,   35,   36,   37,   38,   39,   40,   41,   42,   43,
       44,   45,   24,   46,   47,   48,   49,   50,   24,   24,
       51,   24,   52,   53,   54,   55,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[56] =
    {   0,
        1,    2,    3,    2,    2,    1,    2,    1,    2,    2,
        2,    2,    2,    1,    4,    1,    4,    4,    4,    2,
        1,    2,    1,    4,    4,    1,    1,    1,    2,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    2,    2,    2,    2
    } ;

static yyconst short int yy_base[328] =
    {   0,
        0,    0,  641,  642,   54,   55,  633,  633,   48,  642,
      629,  627,  642,   46,  642,   51,   55,   51,   60,   65,
      642,  629,  642,  620,  642,  642,  642,   61,   66,   70,
       71,   72,   73,   74,   76,   78,   75,   79,   83,   96,
      106,  108,  642,  642,  642,  123,  129,  579,  642,  627,
      626,  619,  616,  585,  642,  642,  117,  134,  129,  140,
      143,  573,  572,  146,  151,  118,  642,  589,  610,  109,
      141,  152,  156,  126,  159,  158,  160,  161,  162,  163,
      164,  167,  168,   88,  175,  165,  172,  169,  176,  177,
      178,   85,  179,  184,  189,  185,  197,  187,  642,  642,

      581,  217,  220,    0,  568,  606,  223,  226,  642,  201,
      195,  206,  207,  211,  231,  233,  188,  606,  234,  237,
      239,  242,  240,  244,  243,  241,  245,  246,  247,  248,
      250,  253,  258,  251,  263,  264,  605,  265,  268,  266,
      269,  271,  583,  275,    0,  642,  282,  285,  603,  275,
      293,  296,  297,  298,  299,  300,  302,  303,  304,  307,
      569,  311,  305,  601,  306,  308,  309,  315,  312,  313,
      316,  318,  319,  321,  317,  322,  323,  324,  337,  576,
      350,  355,  358,  339,  349,  599,  598,  344,  347,  597,
      596,  363,  595,  365,  579,  367,  366,  593,  592,  368,

      369,  372,  375,  373,  374,  377,  378,  382,  591,  381,
      376,  400,  556,  381,  402,  409,  589,  379,  386,  409,
      398,  588,  562,  387,  414,  586,  585,  584,  583,  415,
      417,  582,  418,  408,  419,  422,  429,  556,  428,  432,
      435,  580,  426,  543,  440,  564,  427,  541,  441,  442,
      443,  547,  553,  574,  573,  447,  539,  447,  457,  460,
      571,  555,  454,  549,  568,  552,  456,  566,  565,  533,
      534,  562,  532,  475,  478,  481,  546,  543,  529,  543,
      466,  527,  522,  642,  484,  487,  493,  522,  530,  521,
      519,  549,  642,  513,  496,  499,  502,  464,  471,  642,

      446,  642,  505,  508,  511,  445,  642,  443,  514,  517,
      520,  454,  442,  523,  526,  529,  425,  163,  532,  535,
      642,  642,  642,  554,   88,  557,  561
    } ;

static yyconst short int yy_def[328] =
    {   0,
      323,    1,  323,  323,  323,  323,  323,  324,  323,  323,
      323,  323,  323,  323,  323,  323,  323,  323,  323,  323,
      323,  323,  323,  325,  323,  323,  323,  325,  325,  325,
      325,  325,  325,  325,  325,  325,  325,  325,  325,  325,
      325,  325,  323,  323,  323,  323,  323,  323,  323,  324,
      324,  323,  323,  323,  323,  323,  323,  323,  323,  323,
      323,  323,  326,  323,  323,  323,  323,  323,  325,  325,
      325,  325,  325,  325,  325,  325,  325,  325,  325,  325,
      325,  325,  325,  325,  325,  325,  325,  325,  325,  325,
      325,  325,  325,  325,  325,  325,  325,  325,  323,  323,

      323,  323,  323,  327,  326,  323,  323,  323,  323,  325,
      325,  325,  325,  325,  325,  325,  325,  325,  325,  325,
      325,  325,  325,  325,  325,  325,  325,  325,  325,  325,
      325,  325,  325,  325,  325,  325,  325,  325,  325,  325,
      325,  325,  323,  323,  327,  323,  323,  323,  325,  325,
      325,  325,  325,  325,  325,  325,  325,  325,  325,  325,
      323,  325,  325,  325,  325,  325,  325,  325,  325,  325,
      325,  325,  325,  325,  325,  325,  325,  325,  325,  323,
      323,  323,  323,  325,  325,  325,  325,  325,  325,  325,
      325,  325,  325,  325,  323,  325,  325,  325,  325,  325,

      325,  325,  325,  325,  325,  325,  325,  325,  325,  325,
      325,  325,  323,  323,  323,  323,  325,  325,  325,  325,
      325,  325,  323,  325,  325,  325,  325,  325,  325,  325,
      325,  325,  325,  323,  325,  325,  325,  323,  323,  323,
      323,  325,  325,  323,  325,  323,  325,  323,  325,  325,
      325,  323,  323,  325,  325,  325,  323,  323,  323,  323,
      325,  323,  325,  323,  325,  323,  325,  325,  325,  323,
      323,  325,  323,  323,  323,  323,  323,  323,  323,  323,
      325,  323,  323,  323,  323,  323,  323,  323,  323,  323,
      323,  325,  323,  323,  323,  323,  323,  323,  323,  323,

      323,  323,  323,  323,  323,  323,  323,  323,  323,  323,
      323,  323,  323,  323,  323,  323,  323,  323,  323,  323,
      323,  323,    0,  323,  323,  323,  323
    } ;

static yyconst short int yy_nxt[698] =
    {   0,
        4,    5,    4,    6,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   20,   21,
       22,    4,   23,   24,   24,   25,   26,   27,    4,   28,
       29,   30,   31,   24,   32,   33,   24,   24,   34,   35,
       36,   37,   38,   39,   40,   24,   41,   24,   24,   42,
       24,   43,   44,   45,    4,   46,   46,   46,   47,   52,
       57,   53,   58,   58,   58,   59,   62,   60,   60,   60,
       48,   61,   61,   61,   64,   68,   60,   60,   60,   64,
       68,   60,   65,   65,   68,   68,   68,   68,   68,   68,
       68,   69,   68,   68,   54,   73,   70,   68,   66,   68,

       71,   80,   68,   82,   78,   63,   76,   72,   89,   74,
       68,   75,   84,   77,   79,   86,   81,   83,   88,   85,
       68,   87,   68,   68,   46,   91,   46,   90,  134,  108,
       46,  108,   47,  102,  102,  102,  125,   97,  110,   92,
       68,   98,   93,   94,   48,   61,   61,   61,  103,   95,
       58,   58,   58,   96,   64,   68,   60,   60,   60,   61,
       61,   61,  107,  107,  107,   64,   68,   60,   65,   65,
       68,  115,   68,   68,   68,   68,   68,   68,   68,   68,
      111,   68,   68,   68,   66,  113,   68,  117,  112,   68,
       68,   68,   68,   68,  121,  114,  116,  123,   68,   68,

      119,   68,   68,   68,  127,  322,  118,  128,  120,   68,
      122,   68,  131,  124,  140,   68,  126,  130,  129,  138,
       68,   68,  135,  133,  132,   68,  137,  136,  156,  142,
      139,  150,  141,  102,  102,  102,  144,  144,  144,  147,
      147,  147,  148,  148,  148,   68,  149,   68,   68,  151,
      153,   68,  152,   68,   68,   68,   68,   68,   68,   68,
       68,   68,   68,  166,   68,   68,  154,   68,  161,  155,
      157,  160,   68,  158,  162,  163,  167,   68,   68,   68,
       68,  165,   68,   68,  164,   68,  159,  169,  168,   68,
      170,  181,  181,  181,  175,  171,  172,  176,  182,  182,

      182,  183,  183,  183,  184,  173,  179,   68,  177,  174,
       68,   68,   68,   68,   68,  178,   68,   68,   68,   68,
       68,   68,   68,   68,  199,   68,   68,   68,  189,   68,
       68,   68,   68,   68,  185,   68,   68,   68,   68,  186,
      187,  188,  194,  190,  200,  191,  192,  193,  196,  198,
      197,   68,  201,   68,  206,  210,  203,  211,   68,  202,
      205,   68,  208,   68,  209,  204,  214,  214,  214,  207,
      212,  215,  215,  215,  216,  216,  216,   68,  218,   68,
       68,   68,   68,   68,  217,  219,   68,   68,   68,   68,
       68,   68,   68,   68,  220,   68,   68,  239,  239,  239,

       68,   68,  230,  231,  221,  224,  232,  233,  227,  225,
      234,  235,   68,  222,   68,  228,  226,  229,  240,  240,
      240,  242,  236,   68,  237,  241,  241,  241,   68,   68,
      247,   68,   68,   68,  243,  245,   68,  244,  252,  253,
       68,   68,  248,   68,  258,  258,  258,  251,  259,  259,
      259,  260,  260,  260,   68,   68,   68,   68,  255,  250,
      249,   68,  256,  274,  274,  274,  261,  321,   68,  254,
       68,  318,  265,  275,  275,  275,  276,  276,  276,  263,
       68,  268,  278,  317,  313,  281,  312,  272,  267,  308,
      269,  285,  285,  285,  286,  286,  286,  287,  287,  287,

      295,  295,  295,  296,  296,  296,  307,  306,  292,  297,
      297,  297,  303,  303,  303,  304,  304,  304,  305,  305,
      305,  309,  309,  309,  310,  310,  310,  311,  311,  311,
      314,  314,  314,  315,  315,  315,  316,  316,  316,  319,
      319,  319,  315,  315,  315,  320,  320,  320,  319,  319,
      319,  320,  320,  320,   50,   50,  302,   50,  105,  105,
      105,  145,  145,   68,  145,  301,  300,  299,  298,  294,
      293,  291,  290,  289,  288,  284,   68,  283,  282,   68,
       68,  280,   68,  279,  277,   68,  273,   68,   68,  271,
      270,  266,  264,  262,   68,  257,   68,   68,   68,   68,

       68,  246,   68,   68,  238,   68,   68,   68,  223,   68,
       68,   68,   68,   68,  213,   68,  195,   68,  180,   68,
       68,  146,  106,  143,   68,  109,  106,  104,  101,  100,
       99,   51,   51,   63,   68,   67,   56,   55,   51,   49,
      323,    3,  323,  323,  323,  323,  323,  323,  323,  323,
      323,  323,  323,  323,  323,  323,  323,  323,  323,  323,
      323,  323,  323,  323,  323,  323,  323,  323,  323,  323,
      323,  323,  323,  323,  323,  323,  323,  323,  323,  323,
      323,  323,  323,  323,  323,  323,  323,  323,  323,  323,
      323,  323,  323,  323,  323,  323,  323

    } ;

static yyconst short int yy_chk[698] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    5,    6,    5,    6,    9,
       14,    9,   14,   14,   14,   16,   18,   16,   16,   16,
        6,   17,   17,   17,   19,   28,   19,   19,   19,   20,
       29,   20,   20,   20,   30,   31,   32,   33,   34,   37,
       35,  325,   36,   38,    9,   29,   28,   39,   20,   92,

       28,   32,   84,   34,   31,   18,   30,   28,   38,   29,
       40,   29,   35,   30,   31,   36,   33,   34,   37,   35,
       41,   36,   42,   70,   46,   40,   46,   39,   92,   66,
       47,   66,   47,   57,   57,   57,   84,   42,   70,   40,
       74,   42,   41,   41,   47,   59,   59,   59,   58,   41,
       58,   58,   58,   41,   60,   71,   60,   60,   60,   61,
       61,   61,   64,   64,   64,   65,   72,   65,   65,   65,
       73,   74,   76,   75,   77,   78,   79,   80,   81,   86,
       71,   82,   83,   88,   65,   73,   87,   76,   72,   85,
       89,   90,   91,   93,   80,   73,   75,   82,   94,   96,

       78,   98,  117,   95,   86,  318,   77,   87,   79,  111,
       81,   97,   89,   83,   96,  110,   85,   88,   87,   95,
      112,  113,   93,   91,   90,  114,   94,   93,  117,   98,
       95,  111,   97,  102,  102,  102,  103,  103,  103,  107,
      107,  107,  108,  108,  108,  115,  110,  116,  119,  112,
      114,  120,  113,  121,  123,  126,  122,  125,  124,  127,
      128,  129,  130,  128,  131,  134,  115,  132,  123,  116,
      119,  122,  133,  120,  124,  125,  129,  135,  136,  138,
      140,  127,  139,  141,  126,  142,  121,  131,  130,  150,
      132,  144,  144,  144,  138,  133,  134,  139,  147,  147,

      147,  148,  148,  148,  150,  135,  142,  151,  140,  136,
      152,  153,  154,  155,  156,  141,  157,  158,  159,  163,
      165,  160,  166,  167,  166,  162,  169,  170,  155,  168,
      171,  175,  172,  173,  151,  174,  176,  177,  178,  152,
      153,  154,  160,  156,  167,  157,  158,  159,  162,  165,
      163,  179,  168,  184,  173,  177,  170,  178,  188,  169,
      172,  189,  175,  185,  176,  171,  181,  181,  181,  174,
      179,  182,  182,  182,  183,  183,  183,  192,  185,  194,
      197,  196,  200,  201,  184,  188,  202,  204,  205,  203,
      211,  206,  207,  218,  189,  210,  208,  214,  214,  214,

      219,  224,  204,  205,  192,  196,  206,  207,  201,  197,
      208,  210,  221,  194,  212,  202,  200,  203,  215,  215,
      215,  218,  211,  220,  212,  216,  216,  216,  225,  230,
      224,  231,  233,  235,  219,  221,  236,  220,  234,  234,
      243,  247,  225,  237,  239,  239,  239,  233,  240,  240,
      240,  241,  241,  241,  245,  249,  250,  251,  236,  231,
      230,  256,  237,  258,  258,  258,  243,  317,  263,  235,
      267,  313,  247,  259,  259,  259,  260,  260,  260,  245,
      281,  250,  263,  312,  308,  267,  306,  256,  249,  301,
      251,  274,  274,  274,  275,  275,  275,  276,  276,  276,

      285,  285,  285,  286,  286,  286,  299,  298,  281,  287,
      287,  287,  295,  295,  295,  296,  296,  296,  297,  297,
      297,  303,  303,  303,  304,  304,  304,  305,  305,  305,
      309,  309,  309,  310,  310,  310,  311,  311,  311,  314,
      314,  314,  315,  315,  315,  316,  316,  316,  319,  319,
      319,  320,  320,  320,  324,  324,  294,  324,  326,  326,
      326,  327,  327,  292,  327,  291,  290,  289,  288,  283,
      282,  280,  279,  278,  277,  273,  272,  271,  270,  269,
      268,  266,  265,  264,  262,  261,  257,  255,  254,  253,
      252,  248,  246,  244,  242,  238,  232,  229,  228,  227,

      226,  223,  222,  217,  213,  209,  199,  198,  195,  193,
      191,  190,  187,  186,  180,  164,  161,  149,  143,  137,
      118,  106,  105,  101,   69,   68,   63,   62,   54,   53,
       52,   51,   50,   48,   24,   22,   12,   11,    8,    7,
        3,  323,  323,  323,  323,  323,  323,  323,  323,  323,
      323,  323,  323,  323,  323,  323,  323,  323,  323,  323,
      323,  323,  323,  323,  323,  323,  323,  323,  323,  323,
      323,  323,  323,  323,  323,  323,  323,  323,  323,  323,
      323,  323,  323,  323,  323,  323,  323,  323,  323,  323,
      323,  323,  323,  323,  323,  323,  323

    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "1907048.l"
#define INITIAL 0
#line 21 "1907048.l"
	#include "1907048.tab.h"
	#include <stdio.h>
	#include <stdlib.h>
	#include <string.h>
	int varindex(char *var);
#line 631 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 28 "1907048.l"



#line 786 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 324 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 642 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 31 "1907048.l"
{ printf("single line comment\n"); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 32 "1907048.l"
{ printf("multiple_line_comment\n"); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 35 "1907048.l"
{ return main_function; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 36 "1907048.l"
{ return define; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 39 "1907048.l"
{ return INT; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 40 "1907048.l"
{ return FLOAT; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 41 "1907048.l"
{ return CHAR; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 42 "1907048.l"
{ return DOUBLE; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 43 "1907048.l"
{ return STRING; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 47 "1907048.l"
{ return '('; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 48 "1907048.l"
{ return ')'; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 49 "1907048.l"
{ return '{'; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 50 "1907048.l"
{ return '}'; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 51 "1907048.l"
{ return '['; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 52 "1907048.l"
{ return ']'; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 53 "1907048.l"
{ return END; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 54 "1907048.l"
{ return ','; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 56 "1907048.l"
{ return '+'; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 57 "1907048.l"
{ return '-'; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 58 "1907048.l"
{ return '*'; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 59 "1907048.l"
{ return '/'; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 60 "1907048.l"
{ return '^'; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 61 "1907048.l"
{ return MOD; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 62 "1907048.l"
{ return '&'; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 63 "1907048.l"
{ return '|'; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 64 "1907048.l"
{ return '='; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 65 "1907048.l"
{ return ':';}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 66 "1907048.l"
{ return INC; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 67 "1907048.l"
{ return DEC; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 68 "1907048.l"
{ return NOT; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 71 "1907048.l"
{ return BREAK; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 72 "1907048.l"
{ return CONT; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 73 "1907048.l"
{ return CASE; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 74 "1907048.l"
{ return SWITCH;	}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 75 "1907048.l"
{ return DEFAULT;	}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 78 "1907048.l"
{ return WHILE; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 79 "1907048.l"
{ return FOR; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 80 "1907048.l"
{ return POS_STEP; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 81 "1907048.l"
{ return NEG_STEP; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 84 "1907048.l"
{ return IF; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 85 "1907048.l"
{ return ELIF; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 86 "1907048.l"
{ return ELSE; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 89 "1907048.l"
{ return LT; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 90 "1907048.l"
{ return GT; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 91 "1907048.l"
{ return EQ; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 92 "1907048.l"
{ return GEQ; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 93 "1907048.l"
{ return LEQ; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 94 "1907048.l"
{ return NEQ; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 97 "1907048.l"
{ return SIN; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 98 "1907048.l"
{ return COS; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 99 "1907048.l"
{ return LOG10; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 100 "1907048.l"
{ return ODDEVEN; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 101 "1907048.l"
{ return FACTORIAL;  }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 102 "1907048.l"
{ return MAX; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 103 "1907048.l"
{ return MIN; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 104 "1907048.l"
{ return GCD; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 105 "1907048.l"
{ return LCM; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 106 "1907048.l"
{ return PRIME; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 107 "1907048.l"
{ return SQRT; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 110 "1907048.l"
{ return WRITE; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 111 "1907048.l"
{ return READ; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 114 "1907048.l"
{ 
						yylval.string = strdup(yytext);
					  	return STRING;
					}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 119 "1907048.l"
{ 
						yylval.flt = atof(yytext);
					  	return DOUBLE;
 					}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 124 "1907048.l"
{
						yylval.num = atoi(yytext);
					  	return NUMBER;
					}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 128 "1907048.l"
{
						yylval.num=atoi(yytext);
						return NUMBER;
					}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 134 "1907048.l"
;
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 136 "1907048.l"
{ return IMPORT; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 137 "1907048.l"
{ return HEADER; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 138 "1907048.l"
{ 
	yylval.string = strdup(yytext);
	return VARIABLE; 
	}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 144 "1907048.l"
ECHO;
	YY_BREAK
#line 1234 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 324 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 324 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 323);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 144 "1907048.l"


int yywrap()
{
	return 1;
}

int main()
{
	
	yyin = freopen("input.txt","r",stdin);
	yyout = freopen("output.txt","w",stdout);
	yyparse();
	return 0;
}